---
- name: Download Dependencies
  hosts: kali
  tasks:
    - name: Copy Attackmate Playbook to Kali Machine
      ansible.builtin.copy:
        src: "../attackmate/"
        dest: "/home/superuser/"
        owner: superuser
    - name: Ensure payloads folder exists
      ansible.builtin.file:
        path: /home/superuser/payloads
        state: directory
    - name: Ensure tmp folder exists
      ansible.builtin.file:
        path: /home/superuser/tmp/mimikatz
        state: directory
    - name: Download Mimikatz
      ansible.builtin.get_url:
        url: https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20220919/mimikatz_trunk.zip
        dest: /home/superuser/tmp/mimikatz.zip
    - name: Unzip Mimikatz
      ansible.builtin.unarchive:
        src: /home/superuser/tmp/mimikatz.zip
        dest: /home/superuser/tmp/mimikatz
        remote_src: yes
    - name: Move Mimikatz to /home/superuser/payloads
      shell: mv /home/superuser/tmp/mimikatz/x64/* /home/superuser/payloads/
    - name: Download SharpGPOAbuse
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Flangvik/SharpCollection/master/NetFramework_4.7_Any/SharpGPOAbuse.exe
        dest: /home/superuser/payloads/SharpGPOAbuse.exe
    - name: Download Rubeus
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Flangvik/SharpCollection/master/NetFramework_4.7_Any/Rubeus.exe
        dest: /home/superuser/payloads/Rubeus.exe
    - name: Download NinjaCopy
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/BC-SECURITY/Empire/main/empire/server/data/module_source/collection/Invoke-NinjaCopy.ps1
        dest: /home/superuser/payloads/Invoke-NinjaCopy.ps1
    - name: Fix type casting in Invoke-NinjaCopy.ps1
      ansible.builtin.replace:
        path: /home/superuser/payloads/Invoke-NinjaCopy.ps1
        regexp: '\$PEInfo\.DllCharacteristics'
        replace: '[int]$PEInfo.DllCharacteristics'
    - name: Cleanup
      file:
        path: /home/superuser/tmp
        state: absent

- name: Start msfrpcd
  hosts: kali
  tasks:
    - name: Start msfrpcd
      shell: msfrpcd -P hackerman
