---

- name: Update APT Cache on Linux Machines
  hosts: linux
  become: true
  tasks:
    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: yes

- name: Configure Attacker Machine
  hosts: attacker
  become: true
  vars:
    # attackmate-ansible playbook vars
    attackmate_sliverfix: true
    attackmate_version: development
    attackmate_msf_server: localhost
    attackmate_msf_passwd: hackerman
    command_delay: 2
  roles:
  - attackmate-ansible
  tasks:
    - name: Copy Attackmate Playbook to Attacker Machine
      ansible.builtin.copy:
        src: "../attackmate/killchain.yml"
        dest: "/home/aecid/killchain.yml"
        owner: aecid




# single var for all roles
# - name: Configure Secondary DC
#   hosts: dc2
#   vars:
#     DNSIP: "10.0.0.10"
#   roles:
#   - atb-ansible-msclient
#   - atb-ansible-secondarydc


# multiple vars for multiple roles
# - name: Configure Secondary DC
#   hosts: dc2
#   roles:
#   - role: atb-ansible-msclient
#     vars:
#       DNSIP: "10.0.0.10"
#   - role: atb-ansible-secondarydc
#     vars:
#       DNSIP: "10.0.0.10"
