---
- name: Update APT Cache on Linux Machines
  hosts: linux
  become: true
  tasks:
    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: yes

- name: Configure Keyboard Layout on Windows Machines
  hosts: windows
  gather_facts: no
  tasks:
    - name: Set Keyboard Layout to German
      win_shell: |
        $LangList = New-WinUserLanguageList de-DE
        Set-WinUserLanguageList $LangList -Force

- name: Configure Primary DC
  hosts: dc1
  vars:
    # atb-ansible-primarydc playbook vars
    domainName: "aecid-testbed.com"
  roles:
  - atb-ansible-primarydc

- name: Configure Secondary DC
  hosts: dc2
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "dc2"
  roles:
  - atb-ansible-msclient
  - atb-ansible-secondarydc

- name: Configure Kafka
  hosts: mgmt
  become: true
  vars:
    # atb-ansible-kafka playbook vars
    kafka_listeners: "INTERNAL://localhost:9093,EXTERNAL://:9092"
    kafka_advertised_listeners: "INTERNAL://localhost:9093,EXTERNAL://{{ hostvars['mgmt']['openstack']['addresses']['winlab_network'][0]['addr'] }}:9092"
    kafka_listener_security_proto_map: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  roles:
  - atb-ansible-kafka

- name: Configure WEC
  hosts: wec
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "wec"
    # atb-ansible-windowseventcollector playbook vars
    kafka_broker_ip: "{{ hostvars['mgmt']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
  roles:
  - atb-ansible-msclient
  - atb-ansible-windowseventcollector

- name: Configure Webserver
  hosts: webserver
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "webserver"
    # atb-ansible-winvulnserver playbook vars
    admin_user: "wsadmin@aecid-testbed.com"
    admin_password: "Root.PW1"
  roles:
  - atb-ansible-msclient
  - atb-ansible-winwebserver
  - atb-ansible-winvulnserver

- name: Update Group Policy on Windows Machines
  hosts: windows
  gather_facts: no
  tasks:
    - name: Update Group Policy
      win_command: gpupdate /force

- name: Install Attackmate
  hosts: attacker
  become: true
  vars:
    # attackmate-ansible playbook vars
    attackmate_sliverfix: true
    attackmate_version: development
    attackmate_msf_server: localhost
    attackmate_msf_passwd: hackerman
    command_delay: 2
  roles:
  - attackmate-ansible

- name: Download Binaries
  hosts: attacker
  tasks:
    - name: Copy Attackmate Playbook to Attacker Machine
      ansible.builtin.copy:
        src: "../attackmate/killchain.yml"
        dest: "/home/aecid/killchain.yml"
        owner: aecid
    - name: Ensure payloads folder exists
      ansible.builtin.file:
        path: /home/aecid/payloads
        state: directory
    - name: Ensure tmp folder exists
      ansible.builtin.file:
        path: /home/aecid/tmp/mimikatz
        state: directory
    - name: Download Mimikatz
      ansible.builtin.get_url:
        url: https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20220919/mimikatz_trunk.zip
        dest: /home/aecid/tmp/mimikatz.zip
    - name: Unzip Mimikatz
      ansible.builtin.unarchive:
        src: /home/aecid/tmp/mimikatz.zip
        dest: /home/aecid/tmp/mimikatz
        remote_src: yes
    - name: Move Mimikatz to /home/aecid/payloads
      shell: mv /home/aecid/tmp/mimikatz/x64/* /home/aecid/payloads/
    - name: Clone repository Ghostpack-CompiledBinaries
      git:
        repo: https://github.com/r3motecontrol/Ghostpack-CompiledBinaries.git
        dest: /home/aecid/tmp/Ghostpack-CompiledBinaries
        update: yes
        accept_hostkey: yes
        clone: yes
    - name: Move Rubeus to /home/aecid/payloads
      shell: mv /home/aecid/tmp/Ghostpack-CompiledBinaries/Rubeus.exe /home/aecid/payloads/
    - name: Cleanup
      file:
        path: /home/aecid/tmp
        state: absent



# single var for all roles
# - name: Configure Secondary DC
#   hosts: dc2
#   vars:
#     DNSIP: "10.0.0.10"
#   roles:
#   - atb-ansible-msclient
#   - atb-ansible-secondarydc


# multiple vars for multiple roles
# - name: Configure Secondary DC
#   hosts: dc2
#   roles:
#   - role: atb-ansible-msclient
#     vars:
#       DNSIP: "10.0.0.10"
#   - role: atb-ansible-secondarydc
#     vars:
#       DNSIP: "10.0.0.10"
