---
- name: Configure Primary DC
  hosts: dc1
  vars:
    # atb-ansible-primarydc playbook vars
    domainName: "aecid-testbed.com"
    # atb-ansible-windowseventcollector playbook vars
    kafka_broker_ip: "{{ hostvars['kafka']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
  roles:
  - atb-ansible-primarydc
  - atb-ansible-windowseventcollector

- name: Configure Secondary DC
  hosts: dc2
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "dc2"
  roles:
  - atb-ansible-msclient
  - atb-ansible-secondarydc

- name: Configure Kafka
  hosts: kafka
  become: true
  roles:
  - atb-ansible-kafka

- name: Configure WEC
  hosts: wec
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "wec"
  roles:
  - atb-ansible-msclient

- name: Configure Webserver
  hosts: webserver
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['winlab_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "webserver"
    # atb-ansible-winvulnserver playbook vars
    admin_user: "wsadmin@aecid-testbed.com"
    admin_password: "Root.PW1"
  roles:
  - atb-ansible-msclient
  - atb-ansible-winwebserver
  - atb-ansible-winvulnserver







# single var for all roles
# - name: Configure Secondary DC
#   hosts: dc2
#   vars:
#     DNSIP: "10.0.0.10"
#   roles:
#   - atb-ansible-msclient
#   - atb-ansible-secondarydc


# multiple vars for multiple roles
# - name: Configure Secondary DC
#   hosts: dc2
#   roles:
#   - role: atb-ansible-msclient
#     vars:
#       DNSIP: "10.0.0.10"
#   - role: atb-ansible-secondarydc
#     vars:
#       DNSIP: "10.0.0.10"
