---
- name: Disable Windows Updates
  hosts: windows
  tasks:
  - name: Disable Windows Updates
    win_shell: |
      New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Force | Out-Null
      Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name "NoAutoUpdate" -Value 1 -Type DWord

- name: Update APT Cache on Linux Machines
  hosts: linux
  become: true
  tasks:
    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: yes

- name: Set timezone on Linux machines
  hosts: linux
  become: true
  tasks:
    - name: Set timezone
      shell: timedatectl set-timezone "Europe/Vienna"

- name: Configure Keyboard Layout on Windows Machines
  hosts: windows
  gather_facts: no
  tasks:
    - name: Set Keyboard Layout to German
      win_shell: |
        $LangList = New-WinUserLanguageList de-DE
        Set-WinUserLanguageList $LangList -Force

- name: Configure Primary DC
  hosts: dc1
  vars:
    # atb-ansible-primarydc playbook vars
    domainName: "aecid-testbed.com"
  roles:
  - atb-ansible-primarydc

- name: Configure Kafka
  hosts: mgmt
  become: true
  vars:
    # atb-ansible-kafka playbook vars
    kafka_listeners: "INTERNAL://localhost:9093,EXTERNAL://:9092"
    kafka_advertised_listeners: "INTERNAL://localhost:9093,EXTERNAL://{{ hostvars['mgmt']['openstack']['addresses']['internal_network'][0]['addr'] }}:9092"
    kafka_listener_security_proto_map: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  roles:
  - atb-ansible-kafka

- name: Configure WEC
  hosts: wec
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['internal_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "wec"
    # atb-ansible-windowseventcollector playbook vars
    kafka_broker_ip: "{{ hostvars['mgmt']['openstack']['addresses']['internal_network'][0]['addr'] }}"
  roles:
  - atb-ansible-msclient
  - atb-ansible-windowseventcollector

- name: Configure Webserver
  hosts: web
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['internal_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "web"
    # atb-ansible-winvulnserver playbook vars
    admin_user: "aecid-testbed.com\\wsadmin"
    admin_password: "Root.PW1"
    compromised_user: "aecid-testbed.com\\Alice"
  roles:
  - atb-ansible-msclient
  - atb-ansible-winvulnserver

- name: Update Group Policy on Windows Machines
  hosts: windows
  gather_facts: no
  tasks:
    - name: Update Group Policy
      win_command: gpupdate /force

- name: Install Attackmate
  hosts: kali
  become: true
  vars:
    # attackmate-ansible playbook vars
    attackmate_sliverfix: false
    attackmate_version: development
    attackmate_msf_server: localhost
    attackmate_msf_passwd: hackerman
    command_delay: 15
  roles:
  - attackmate-ansible

- name: Install Dependencies
  hosts: kali
  become: true
  tasks:
    - name: Install unzip
      apt:
        name:
          - unzip
          - evil-winrm
          # - metasploit-framework # install an older version instead, there is a bug in attackmate with metasploit version >= 6.4.74
        state: present
        update_cache: yes

- name: Install Metasploit v.6.4.64
  hosts: kali
  become: true
  vars:
    msf_deb_url: "https://old.kali.org/kali/pool/main/m/metasploit-framework/metasploit-framework_6.4.64-0kali1_amd64.deb"
    msf_deb_path: "/tmp/metasploit-framework_6.4.64-0kali1_amd64.deb"
  tasks:
    - name: Download Metasploit .deb package
      get_url:
        url: "{{ msf_deb_url }}"
        dest: "{{ msf_deb_path }}"
    - name: Install .deb package
      apt:
        deb: "{{ msf_deb_path }}"
        state: present

- name: Download Dependencies
  hosts: kali
  tasks:
    - name: Copy Attackmate Playbook to Kali Machine
      ansible.builtin.copy:
        src: "../attackmate/"
        dest: "/home/superuser/"
        owner: superuser
    - name: Ensure payloads folder exists
      ansible.builtin.file:
        path: /home/superuser/payloads
        state: directory
    - name: Ensure tmp folder exists
      ansible.builtin.file:
        path: /home/superuser/tmp/mimikatz
        state: directory
    - name: Download Mimikatz
      ansible.builtin.get_url:
        url: https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20220919/mimikatz_trunk.zip
        dest: /home/superuser/tmp/mimikatz.zip
    - name: Unzip Mimikatz
      ansible.builtin.unarchive:
        src: /home/superuser/tmp/mimikatz.zip
        dest: /home/superuser/tmp/mimikatz
        remote_src: yes
    - name: Move Mimikatz to /home/superuser/payloads
      shell: mv /home/superuser/tmp/mimikatz/x64/* /home/superuser/payloads/
    - name: Download SharpGPOAbuse
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Flangvik/SharpCollection/master/NetFramework_4.7_Any/SharpGPOAbuse.exe
        dest: /home/superuser/payloads/SharpGPOAbuse.exe
    - name: Download Rubeus
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Flangvik/SharpCollection/master/NetFramework_4.7_Any/Rubeus.exe
        dest: /home/superuser/payloads/Rubeus.exe
    - name: Download NinjaCopy
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/BC-SECURITY/Empire/main/empire/server/data/module_source/collection/Invoke-NinjaCopy.ps1
        dest: /home/superuser/payloads/Invoke-NinjaCopy.ps1
    - name: Fix type casting in Invoke-NinjaCopy.ps1
      ansible.builtin.replace:
        path: /home/superuser/payloads/Invoke-NinjaCopy.ps1
        regexp: '\$PEInfo\.DllCharacteristics'
        replace: '[int]$PEInfo.DllCharacteristics'
    - name: Cleanup
      file:
        path: /home/superuser/tmp
        state: absent

- name: Start msfrpcd
  hosts: kali
  tasks:
    - name: Start msfrpcd
      shell: msfrpcd -P hackerman
