- name: Configure Webserver
  hosts: web
  vars:
    # atb-ansible-msclient playbook vars
    DNSIP: "{{ hostvars['dc1']['openstack']['addresses']['internal_network'][0]['addr'] }}"
    domainName: "aecid-testbed.com"
    domainAdminAccount: "administrator@aecid-testbed.com"
    domainAdminPassword: "%A%4N1lmLFUFTzs4#XnI"
    hostname: "web"
    # atb-ansible-winvulnserver playbook vars
    admin_user: "aecid-testbed.com\\wsadmin"
    admin_password: "Root.PW1"
    compromised_user: "aecid-testbed.com\\Alice"
  tasks:
  - name: Changing the password of Administrator
    ansible.windows.win_user:
      name: "administrator"
      password: "P@ssword123"
      update_password: always
      state: present
